name: SBT Check Build

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  sbt-check-test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    
    # Configure the below sbt check command as per you project requirement
    - name: Run test cases and generate reports
      run: |
        sbt cpd
        sbt scapegoat
        sbt scalastyle
        sbt coverage test coverageReport
        sbt sonarScan 

    # Build the Docker image
    - name: Package and Build
      working-directory: app
      run: |
        sbt docker:publishLocal
